name: Calculate unit tests coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAKE_TERMOUT: 1
      CMAKE_COLOR_DIAGNOSTICS: ON
      GTEST_COLOR: yes

    steps:
      - name: Install Gcovr
        run: pip install gcovr

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate unit tests coverage
        run: ./build.sh --no-sanitizer --test-coverage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: G-PIES
          path: ./out/*
      - name: Upload the coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Test coverage
          path: ./.build/test_coverage/*
