name: Build and run tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-14 ]
        configuration: [ Debug, Release ]
        include:
          - os: windows-latest
            cuda: true
            metal: false
          - os: ubuntu-latest
            cuda: true
            metal: false
          - os: macos-14
            cuda: false
            metal: true

    runs-on: ${{ matrix.os }}

    env:
      MAKE_TERMOUT: 1
      CMAKE_COLOR_DIAGNOSTICS: ON
      GTEST_COLOR: yes
      out_dir: ${{ startsWith(matrix.os, 'windows') && format('./out/{0}', matrix.configuration) || './out' }}
      cuda_install_method: ${{ startsWith(matrix.os, 'windows') && 'local' || 'network' }}
      cuda_packages: ${{ startsWith(matrix.os, 'windows') && '[ "nvcc", "cudart", "visual_studio_integration" ]' || '[ "nvcc" ]' }}
      cmake_preset: ${{ matrix.cuda && 'cuda-all-major' || matrix.metal && 'metal' || 'default' }}

    steps:
      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.14
        with:
          cuda: '12.3.2'
          method: network
          sub-packages: ${{ env.cuda_packages }}
          log-file-suffix: ${{ matrix.configuration }}-${{ matrix.os }}-log.txt
        if: ${{ matrix.cuda }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate the buildsystem
        run: cmake -B ./build -S . --preset ${{ env.cmake_preset }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build
        run: cmake --build ./build -j4 --config ${{ matrix.configuration }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: G-PIES ${{ matrix.configuration }} ${{ matrix.os }}
          path: ${{ env.out_dir }}/*
      
      - name: Run Cluster Dynamics Tests
        run: ${{ env.out_dir }}/cd_tests
      - name: Run DB Tests
        run: ${{ env.out_dir }}/db_tests
