name: Build and deploy GitHub pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz
      - name: Configure Doxygen
        run: echo "GPIES__STRIP_FROM_PATH=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
      - name: Build Doxygen site
        run: cd ./docs && doxygen ./BackendDoxyfile
      - name: git status
        run: git status
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
