name: Build and run tests (Windows)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [ debug, release ]

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: make cdex -d

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: G-PIES ${{ matrix.configuration }}
          path: |
            build/${{ matrix.configuration }}/cd_cuda_example.exe
