name: Build and run tests (macOS)

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        configuration: [debug, release]

    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build CPU targets
        run: make all_cpu CONFIGURATION=${{ matrix.configuration }}
