name: Build and run tests (Linux)

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Jimver/cuda-toolkit@v0.2.14
        id: cuda-toolkit
        with:
          cuda: '12.3.2'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build CPU targets
        run: make all_cpu all dbtests

      - name: Run Cluster Dynamics Tests
        run: ./build/release/cd_tests
      - name: Run Client Database Tests
        run: ./bin/db_tests.out

      - name: Upload Cluster Dynamics Executable
        uses: actions/upload-artifact@v2
        with:
          name: cluster_dynamics
          path: bin/cluster_dynamics.out

      - name: Upload Client Database Executable 
        uses: actions/upload-artifact@v2
        with:
          name: client_db 
          path: bin/client_db.out
